name: PHP CI/CD Pipeline

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  security-events: write
  actions: read
  packages: write
  
env:
  REGISTRY: ghcr.io
  # IMAGE_REPOSITORY will be used as a prefix for both images (e.g., ghcr.io/your-org/your-repo-php-rr)
  IMAGE_REPOSITORY: ${{ github.repository }} 

jobs:
  
  build-and-push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' # Changed 'main' to 'master' for push branch
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercase repository name
      run: echo "REPO_LC=$(echo ${{ env.IMAGE_REPOSITORY }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Extract metadata for php-rr image
      id: meta-rr
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.REPO_LC }}-php-rr # Image name with -php-rr suffix
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push php-rr Docker image
      uses: docker/build-push-action@v6
      with:
        context: . # Context is the root of the checked-out repository (php-rr-benchmark/php-rr)
        file: Dockerfile.php-rr # Path to Dockerfile for php-rr relative to context
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta-rr.outputs.tags }}
        labels: ${{ steps.meta-rr.outputs.labels }}
        cache-from: |
          type=gha
          type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LC }}-php-rr:buildcache
        cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LC }}-php-rr:buildcache,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        no-cache-filters: |
          .git
          .github
          **/*.md
          **/*.txt

    - name: Extract metadata for php-fpm image
      id: meta-fpm
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.REPO_LC }}-php-fpm # Image name with -php-fpm suffix
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push php-fpm Docker image
      uses: docker/build-push-action@v6
      with:
        context: . # Context is the root of the checked-out repository (php-rr-benchmark/php-rr)
        file: Dockerfile.php-fpm # Path to Dockerfile for php-fpm relative to context
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta-fpm.outputs.tags }}
        labels: ${{ steps.meta-fpm.outputs.labels }}
        cache-from: |
          type=gha
          type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LC }}-php-fpm:buildcache
        cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LC }}-php-fpm:buildcache,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        no-cache-filters: |
          .git
          .github
          **/*.md
          **/*.txt 